# مشروع تنظيف ومعالجة بيانات المبيعات (Sales Data Cleaning & Manipulation)

يحتوي هذا الملف على الخطوات الكاملة لإنشاء البيانات، فحصها، وتطبيق عمليات التنظيف والتحليل المطلوبة باستخدام مكتبة **Pandas** خطوة بخطوة.

### 1. استيراد المكتبات وبناء الـ DataFrame والفحص الأولي
نقوم باستيراد المكتبات الأساسية وتوليد البيانات لفحصها باستخدام `head()` و `info()` و `describe()`.

In [15]:
import pandas as pd
import numpy as np

In [16]:
data = {
    'OrderID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Product': ['iPhone', 'Samsung S23', 'iPhone', 'MacBook', 'Samsung S23', 'iPad', 'MacBook', 'iPhone'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Computers', 'Electronics', 'Electronics', 'Computers', 'Electronics'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Sales': [1200, 950, 1200, 2500, None, 600, 2500, 1200], 
    'Quantity': [2, 1, 2, 1, 3, np.nan, 2, 1],
    'OrderDate': ['2026-01-15', '2026-01-16', '2026-01-16', '2026-01-17', '2026-01-18', '2026-01-19', '2026-01-20', '2026-01-20']
}

df = pd.DataFrame(data)

In [17]:
# عرض أول 5 صفوف
df.head()

   OrderID      Product     Category Region   Sales  Quantity   OrderDate
0      101       iPhone  Electronics  North  1200.0       2.0  2026-01-15
1      102  Samsung S23  Electronics  South   950.0       1.0  2026-01-16
2      103       iPhone  Electronics   East  1200.0       2.0  2026-01-16
3      104      MacBook    Computers   West  2500.0       1.0  2026-01-17
4      105  Samsung S23  Electronics  North     NaN       3.0  2026-01-18

In [18]:
# فحص جودة وأنواع البيانات والتعرف على القيم المفقودة
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    8 non-null      int64
 1   Product    8 non-null      str
 2   Category   8 non-null      str
 3   Region     8 non-null      str
 4   Sales      7 non-null      float64
 5   Quantity   7 non-null      float64
 6   OrderDate  8 non-null      str
dtypes: float64(2), int64(1), str(4)
memory usage: 580.0 bytes

In [19]:
# الإحصاءات الوصفية للبيانات الرقمية
df.describe()

         OrderID        Sales  Quantity
count    8.00000     7.000000  7.000000
mean   104.50000  1450.000000  1.714286
std      2.44949   748.888065  0.755929
min    101.00000   600.000000  1.000000
25%    102.75000  1075.000000  1.000000
50%    104.50000  1200.000000  2.000000
75%    106.25000  1850.000000  2.000000
max    108.00000  2500.000000  3.000000

### 2. معالجة وتصحيح أنواع البيانات (Data Types)
تحويل الأعمدة إلى أنواع البيانات المناسبة لكل منها لضمان دقة العمليات الحسابية والزمنية اللاحقة.

In [20]:
df['Quantity'] = df['Quantity'].astype('Int32')
df['OrderDate'] = df['OrderDate'].astype('datetime64[us]')
print(df.dtypes)

OrderID               int64
Product                 str
Category                str
Region                  str
Sales               float64
Quantity              Int32
OrderDate    datetime64[us]
dtype: object

### 3. اكتشاف ومعالجة القيم المفقودة (Missing Values)
التحقق من مواضع الفراغات ومعالجتها عن طريق استبدالها بقيم منطقية أو ثابتة.

In [21]:
# التحقق من وجود القيم المفقودة
df.isnull().sum()

OrderID      0
Product      0
Category     0
Region       0
Sales        1
Quantity     1
OrderDate    0
dtype: int64

In [22]:
# معالجة القيم المفقودة
df['Quantity'] = df['Quantity'].fillna(6)
df['Sales'] = df['Sales'].fillna(800).astype('float64')
df

   OrderID      Product     Category Region   Sales  Quantity  OrderDate
0      101       iPhone  Electronics  North  1200.0         2 2026-01-15
1      102  Samsung S23  Electronics  South   950.0         1 2026-01-16
2      103       iPhone  Electronics   East  1200.0         2 2026-01-16
3      104      MacBook    Computers   West  2500.0         1 2026-01-17
4      105  Samsung S23  Electronics  North   800.0         3 2026-01-18
5      106         iPad  Electronics  South   600.0         6 2026-01-19
6      107      MacBook    Computers   East  2500.0         2 2026-01-20
7      108       iPhone  Electronics   West  1200.0         1 2026-01-20

### 4. تطبيق التصفية (Filtering)
استخراج البيانات بناءً على شروط مخصصة مدمجة باستخدام معامل التصفية المنطقي (OR).

In [23]:
custom_filter_df = df[(df['Region'] == 'North') | (df['Product'] == 'iPhone') | (df['Sales'] > 1000)]
print(custom_filter_df)

   OrderID      Product     Category Region   Sales  Quantity  OrderDate
0      101       iPhone  Electronics  North  1200.0         2 2026-01-15
2      103       iPhone  Electronics   East  1200.0         2 2026-01-16
3      104      MacBook    Computers   West  2500.0         1 2026-01-17
4      105  Samsung S23  Electronics  North   800.0         3 2026-01-18
6      107      MacBook    Computers   East  2500.0         2 2026-01-20
7      108       iPhone  Electronics   West  1200.0         1 2026-01-20

### 5. تجميع البيانات وتحليلها باستخدام `groupby()`
حساب إجمالي المبيعات ومتوسط المبيعات لكل فئة من المنتجات مع تنظيم أسماء الأعمدة الناتجة.

In [24]:
category_summary = df.groupby('Category')['Sales'].agg(['sum', 'mean'])
category_summary = category_summary.rename(columns={
    'sum': 'Total_Sales',
    'mean': 'Average_Sales'
})
print(category_summary)

             Total_Sales  Average_Sales
Category
Computers         5000.0    2500.000000
Electronics       5950.0     991.666667

### 6. إتمام عمليات التنظيف وحفظ النسخة النهائية

In [25]:
df.to_csv('final_cleaned_sales_data.csv', index=False)
print("تم حفظ النسخة النهائية بنجاح !")

تم حفظ النسخة النهائية بنجاح !